// Code generated by swagger-doc. DO NOT EDIT.

package v1alpha1

func (VirtualMachineTemplate) SwaggerDoc() map[string]string {
	return map[string]string{
		"": "+genclient\n+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object\n+kubebuilder:object:root=true\n+kubebuilder:resource:path=virtualmachinetemplates,singular=virtualmachinetemplate,categories=all",
	}
}

func (VirtualMachineTemplateSpec) SwaggerDoc() map[string]string {
	return map[string]string{
		"message":        "message is an optional instructional message that will\nbe displayed when this template is instantiated.\nThis field should inform the user how to utilize the newly created resources.\nParameter substitution will be performed on the message before being\ndisplayed so that generated credentials and other parameters can be\nincluded in the output.",
		"virtualMachine": "+kubebuilder:pruning:PreserveUnknownFields",
		"parameters":     "parameters is an optional array of Parameters used during the\nTemplate to Config transformation.",
	}
}

func (VirtualMachineTemplateList) SwaggerDoc() map[string]string {
	return map[string]string{
		"":      "+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object\n+kubebuilder:object:root=true\nVirtualMachineTemplateList is a list of Template objects.",
		"items": "items is a list of templates",
	}
}

func (Parameter) SwaggerDoc() map[string]string {
	return map[string]string{
		"":            "Parameter defines a name/value variable that is to be processed during\nthe Template to Config transformation.",
		"name":        "name must be set and it can be referenced in Template\nItems using ${PARAMETER_NAME}. Required.\n+kubebuilder:validation:Required",
		"displayName": "Optional: The name that will show in UI instead of parameter 'Name'",
		"description": "description of a parameter. Optional.",
		"value":       "value holds the Parameter data. If specified, the generator will be\nignored. The value replaces all occurrences of the Parameter ${Name}\nexpression during the Template to Config transformation. Optional.",
		"generate":    "generate specifies the generator to be used to generate random string\nfrom an input value specified by From field. The result string is\nstored into Value field. If empty, no generator is being used, leaving\nthe result Value untouched. Optional.\n\nThe only supported generator is \"expression\", which accepts a \"from\"\nvalue in the form of a simple regular expression containing the\nrange expression \"[a-zA-Z0-9]\", and the length expression \"a{length}\".\n\nExamples:\n\nfrom             | value",
		"from":        "from is an input value for the generator. Optional.",
		"required":    "Optional: Indicates the parameter must have a value.  Defaults to false.",
	}
}

func (VirtualMachineTemplateRequest) SwaggerDoc() map[string]string {
	return map[string]string{
		"":       "+genclient\n+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object\n+kubebuilder:object:root=true\n+kubebuilder:resource:path=virtualmachinetemplaterequests,singular=virtualmachinetemplaterequest,categories=all\n+kubebuilder:subresource:status",
		"spec":   "spec defines the desired state of VirtualMachineTemplateRequest",
		"status": "status defines the observed state of VirtualMachineTemplateRequest",
	}
}

func (VirtualMachineTemplateRequestSpec) SwaggerDoc() map[string]string {
	return map[string]string{
		"source": "source is a reference to the VirtualMachine to create a template from\n+kubebuilder:validation:Required",
	}
}

func (VirtualMachineTemplateRequestStatus) SwaggerDoc() map[string]string {
	return map[string]string{
		"phase":              "phase represents the current phase of the template request",
		"snapshot":           "snapshot references the VirtualMachineSnapshot created for this request",
		"template":           "template references the VirtualMachineTemplate created from this request",
		"conditions":         "conditions represent the latest available observations of the template request's current state\n+listType=map\n+listMapKey=type",
		"observedGeneration": "observedGeneration is the most recent generation observed for this resource",
	}
}

func (VirtualMachineReference) SwaggerDoc() map[string]string {
	return map[string]string{
		"":          "VirtualMachineReference represents a reference to a VirtualMachine",
		"name":      "name is the name of the VirtualMachine\n+kubebuilder:validation:Required",
		"namespace": "namespace is the namespace of the VirtualMachine\nIf not specified, defaults to the same namespace as the request",
	}
}

func (VirtualMachineTemplateRequestCondition) SwaggerDoc() map[string]string {
	return map[string]string{
		"":                   "VirtualMachineTemplateRequestCondition represents a condition of a VirtualMachineTemplateRequest",
		"type":               "type of the condition",
		"status":             "status of the condition, one of True, False, Unknown",
		"lastTransitionTime": "lastTransitionTime is the last time the condition transitioned from one status to another",
		"reason":             "reason is a unique, one-word, CamelCase reason for the condition's last transition",
		"message":            "message is a human-readable message indicating details about the transition",
	}
}

func (VirtualMachineTemplateRequestList) SwaggerDoc() map[string]string {
	return map[string]string{
		"":      "VirtualMachineTemplateRequestList is a list of VirtualMachineTemplateRequest objects.",
		"items": "items is a list of VirtualMachineTemplateRequest objects",
	}
}
