// Code generated by swagger-doc. DO NOT EDIT.

package v1alpha1

func (VirtualMachineTemplate) SwaggerDoc() map[string]string {
	return map[string]string{
		"": "+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object\n+genclient",
	}
}

func (VirtualMachineTemplateList) SwaggerDoc() map[string]string {
	return map[string]string{
		"": "+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object",
	}
}

func (VirtualMachineTemplateSpec) SwaggerDoc() map[string]string {
	return map[string]string{
		"virtualMachine":            "A static VirtualMachine definition\n+optional",
		"virtualMachineRef":         "A reference to an existing VirtualMachine\n+optional",
		"virtualMachineSnapshotRef": "A reference to an existing VirtualMachineSnapshotRef\n+optional",
	}
}

func (VirtualMachineTemplateStatus) SwaggerDoc() map[string]string {
	return map[string]string{
		"virtualMachineSnapshotRef": "A reference to a captured VirtualMachineSnapshotRef\n+optional",
	}
}
