/*
This file is part of the KubeVirt project

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Copyright The KubeVirt Authors.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubevirt.io/api/template/v1alpha1"
)

// FakeVirtualMachineTemplateRequests implements VirtualMachineTemplateRequestInterface
type FakeVirtualMachineTemplateRequests struct {
	Fake *FakeTemplateV1alpha1
	ns   string
}

var virtualmachinetemplaterequestsResource = v1alpha1.SchemeGroupVersion.WithResource("virtualmachinetemplaterequests")

var virtualmachinetemplaterequestsKind = v1alpha1.SchemeGroupVersion.WithKind("VirtualMachineTemplateRequest")

// Get takes name of the virtualMachineTemplateRequest, and returns the corresponding virtualMachineTemplateRequest object, and an error if there is any.
func (c *FakeVirtualMachineTemplateRequests) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VirtualMachineTemplateRequest, err error) {
	emptyResult := &v1alpha1.VirtualMachineTemplateRequest{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(virtualmachinetemplaterequestsResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.VirtualMachineTemplateRequest), err
}

// List takes label and field selectors, and returns the list of VirtualMachineTemplateRequests that match those selectors.
func (c *FakeVirtualMachineTemplateRequests) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VirtualMachineTemplateRequestList, err error) {
	emptyResult := &v1alpha1.VirtualMachineTemplateRequestList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(virtualmachinetemplaterequestsResource, virtualmachinetemplaterequestsKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VirtualMachineTemplateRequestList{ListMeta: obj.(*v1alpha1.VirtualMachineTemplateRequestList).ListMeta}
	for _, item := range obj.(*v1alpha1.VirtualMachineTemplateRequestList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested virtualMachineTemplateRequests.
func (c *FakeVirtualMachineTemplateRequests) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(virtualmachinetemplaterequestsResource, c.ns, opts))

}

// Create takes the representation of a virtualMachineTemplateRequest and creates it.  Returns the server's representation of the virtualMachineTemplateRequest, and an error, if there is any.
func (c *FakeVirtualMachineTemplateRequests) Create(ctx context.Context, virtualMachineTemplateRequest *v1alpha1.VirtualMachineTemplateRequest, opts v1.CreateOptions) (result *v1alpha1.VirtualMachineTemplateRequest, err error) {
	emptyResult := &v1alpha1.VirtualMachineTemplateRequest{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(virtualmachinetemplaterequestsResource, c.ns, virtualMachineTemplateRequest, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.VirtualMachineTemplateRequest), err
}

// Update takes the representation of a virtualMachineTemplateRequest and updates it. Returns the server's representation of the virtualMachineTemplateRequest, and an error, if there is any.
func (c *FakeVirtualMachineTemplateRequests) Update(ctx context.Context, virtualMachineTemplateRequest *v1alpha1.VirtualMachineTemplateRequest, opts v1.UpdateOptions) (result *v1alpha1.VirtualMachineTemplateRequest, err error) {
	emptyResult := &v1alpha1.VirtualMachineTemplateRequest{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(virtualmachinetemplaterequestsResource, c.ns, virtualMachineTemplateRequest, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.VirtualMachineTemplateRequest), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVirtualMachineTemplateRequests) UpdateStatus(ctx context.Context, virtualMachineTemplateRequest *v1alpha1.VirtualMachineTemplateRequest, opts v1.UpdateOptions) (result *v1alpha1.VirtualMachineTemplateRequest, err error) {
	emptyResult := &v1alpha1.VirtualMachineTemplateRequest{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(virtualmachinetemplaterequestsResource, "status", c.ns, virtualMachineTemplateRequest, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.VirtualMachineTemplateRequest), err
}

// Delete takes name of the virtualMachineTemplateRequest and deletes it. Returns an error if one occurs.
func (c *FakeVirtualMachineTemplateRequests) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(virtualmachinetemplaterequestsResource, c.ns, name, opts), &v1alpha1.VirtualMachineTemplateRequest{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVirtualMachineTemplateRequests) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(virtualmachinetemplaterequestsResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.VirtualMachineTemplateRequestList{})
	return err
}

// Patch applies the patch and returns the patched virtualMachineTemplateRequest.
func (c *FakeVirtualMachineTemplateRequests) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VirtualMachineTemplateRequest, err error) {
	emptyResult := &v1alpha1.VirtualMachineTemplateRequest{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(virtualmachinetemplaterequestsResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.VirtualMachineTemplateRequest), err
}
